### ISSUE TITLE
Minecart Chests Not Rendering

### ISSUE THREAD

**Issue by AyushGuha6** [FoundationGames/EnhancedBlockEntities#14]
Minecart with chests do not render the chest inside, only the minecart itself renders, even with no other mods

**Comment by FoundationGames** [comment]
Known issue, fixed in development

**Comment by hugeblank** [comment]
this also seems to effect chests on their own, but this may be another mod conflicting. I haven't had the time to do a standalone test.

**Comment by FoundationGames** [comment]
@hugeblank please remember to read the mod description, Sodium will make chests invisible unless you use Indium with the mod

**Comment by hgorski6** [comment]
> @hugeblank please remember to read the mod description, Sodium will make chests invisible unless you use Indium with the mod

I set up the mod according to the guide of setting it up with sodium (which means indium's included), and the chests are still not rendering
Log of the gameplay where I noticed that: https://pastebin.com/p1sruWw7

**Comment by FoundationGames** [comment]
Fixed in 0.2
